version: '3.8'

services:
  bot:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo_data:
